[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.mainnet]
losbros_nft_program = "G2P93mEMB46JhuA6rWRUMWZNJFEHJ5Bc1mUNetbUH7wR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = '~\.config\solana\id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
