[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

# Analos-specific configuration
[programs.analos]
analos_nft_launcher_program = "9dEJ2oK4cgDE994FU9za4t2BN7mFwSCfhSsLTGD3a4ym"

[programs.devnet]
analos_nft_launcher_program = "9dEJ2oK4cgDE994FU9za4t2BN7mFwSCfhSsLTGD3a4ym"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "analos"
wallet = '~\.config\solana\id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
build-analos = "anchor build --arch sbf"
deploy-analos = "anchor deploy --provider.cluster analos"
