[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.mainnet]
simple_nft_program = "Db5DnDBJbMDMd4vMgebjSfNCL8SEJZySWawKfxJd2rSw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = '~\.config\solana\id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
