name: Build Solana Programs

on:
  workflow_dispatch:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libudev-dev pkg-config libssl-dev
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Install Solana
      run: |
        sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
        echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
        export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
        solana --version
        solana-install init 1.18.26
    
    - name: Install Anchor
      run: |
        cargo install --git https://github.com/coral-xyz/anchor anchor-cli --locked --force
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Build Programs
      run: |
        anchor build
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: solana-programs
        path: |
          target/deploy/*.so
          target/deploy/*-keypair.json
          target/idl/*.json

