name: Build Price Oracle (Direct)

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Solana CLI
      run: |
        sh -c "$(curl -sSfL https://release.solana.com/v1.18.26/install)"
        echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
        
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Verify Solana Installation
      run: |
        $HOME/.local/share/solana/install/active_release/bin/solana --version
        ls -la $HOME/.local/share/solana/install/active_release/bin/
        
    - name: Build Program using cargo build-sbf
      run: |
        cd programs/analos-price-oracle
        $HOME/.local/share/solana/install/active_release/bin/cargo-build-sbf
        
    - name: Show Build Output
      run: |
        echo "Build completed successfully!"
        ls -la programs/analos-price-oracle/target/deploy/
        echo "Program binary size:"
        ls -lh programs/analos-price-oracle/target/deploy/*.so
        
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: price-oracle-binary
        path: programs/analos-price-oracle/target/deploy/analos_price_oracle.so
        
    - name: Create Deployment Summary
      run: |
        echo "## 🚀 Price Oracle Program Built Successfully!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 📦 Build Details:" >> $GITHUB_STEP_SUMMARY
        echo "- **Program ID:** AaKR2YwrRFohmyUnWLhaVt43Ung6CgAeW43A119i94Vw" >> $GITHUB_STEP_SUMMARY
        echo "- **Binary:** analos_price_oracle.so" >> $GITHUB_STEP_SUMMARY
        echo "- **Size:** $(ls -lh programs/analos-price-oracle/target/deploy/analos_price_oracle.so | awk '{print $5}')" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 📥 Download Binary:" >> $GITHUB_STEP_SUMMARY
        echo "Download the artifact from the Actions tab above." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 🎯 Deployment Instructions:" >> $GITHUB_STEP_SUMMARY
        echo '```bash' >> $GITHUB_STEP_SUMMARY
        echo 'solana program deploy analos_price_oracle.so \' >> $GITHUB_STEP_SUMMARY
        echo '  --program-id AaKR2YwrRFohmyUnWLhaVt43Ung6CgAeW43A119i94Vw \' >> $GITHUB_STEP_SUMMARY
        echo '  --url https://rpc.analos.io \' >> $GITHUB_STEP_SUMMARY
        echo '  --use-rpc' >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY

